package com.example.demo.domain;

import java.math.BigDecimal;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbg.generated Sun Sep 30 17:07:10 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_name
     *
     * @mbg.generated Sun Sep 30 17:07:10 CST 2018
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_tile
     *
     * @mbg.generated Sun Sep 30 17:07:10 CST 2018
     */
    private String goodsTile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_img
     *
     * @mbg.generated Sun Sep 30 17:07:10 CST 2018
     */
    private String goodsImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_price
     *
     * @mbg.generated Sun Sep 30 17:07:10 CST 2018
     */
    private BigDecimal goodsPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_stock
     *
     * @mbg.generated Sun Sep 30 17:07:10 CST 2018
     */
    private String goodsStock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_detail
     *
     * @mbg.generated Sun Sep 30 17:07:10 CST 2018
     */
    private String goodsDetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbg.generated Sun Sep 30 17:07:10 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbg.generated Sun Sep 30 17:07:10 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_name
     *
     * @return the value of goods.goods_name
     *
     * @mbg.generated Sun Sep 30 17:07:10 CST 2018
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_name
     *
     * @param goodsName the value for goods.goods_name
     *
     * @mbg.generated Sun Sep 30 17:07:10 CST 2018
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_tile
     *
     * @return the value of goods.goods_tile
     *
     * @mbg.generated Sun Sep 30 17:07:10 CST 2018
     */
    public String getGoodsTile() {
        return goodsTile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_tile
     *
     * @param goodsTile the value for goods.goods_tile
     *
     * @mbg.generated Sun Sep 30 17:07:10 CST 2018
     */
    public void setGoodsTile(String goodsTile) {
        this.goodsTile = goodsTile == null ? null : goodsTile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_img
     *
     * @return the value of goods.goods_img
     *
     * @mbg.generated Sun Sep 30 17:07:10 CST 2018
     */
    public String getGoodsImg() {
        return goodsImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_img
     *
     * @param goodsImg the value for goods.goods_img
     *
     * @mbg.generated Sun Sep 30 17:07:10 CST 2018
     */
    public void setGoodsImg(String goodsImg) {
        this.goodsImg = goodsImg == null ? null : goodsImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_price
     *
     * @return the value of goods.goods_price
     *
     * @mbg.generated Sun Sep 30 17:07:10 CST 2018
     */
    public BigDecimal getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_price
     *
     * @param goodsPrice the value for goods.goods_price
     *
     * @mbg.generated Sun Sep 30 17:07:10 CST 2018
     */
    public void setGoodsPrice(BigDecimal goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_stock
     *
     * @return the value of goods.goods_stock
     *
     * @mbg.generated Sun Sep 30 17:07:10 CST 2018
     */
    public String getGoodsStock() {
        return goodsStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_stock
     *
     * @param goodsStock the value for goods.goods_stock
     *
     * @mbg.generated Sun Sep 30 17:07:10 CST 2018
     */
    public void setGoodsStock(String goodsStock) {
        this.goodsStock = goodsStock == null ? null : goodsStock.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_detail
     *
     * @return the value of goods.goods_detail
     *
     * @mbg.generated Sun Sep 30 17:07:10 CST 2018
     */
    public String getGoodsDetail() {
        return goodsDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_detail
     *
     * @param goodsDetail the value for goods.goods_detail
     *
     * @mbg.generated Sun Sep 30 17:07:10 CST 2018
     */
    public void setGoodsDetail(String goodsDetail) {
        this.goodsDetail = goodsDetail == null ? null : goodsDetail.trim();
    }
}