package com.example.demo.domain;

public class Memberinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberInfo.id
     *
     * @mbg.generated Fri Sep 28 14:26:35 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberInfo.username
     *
     * @mbg.generated Fri Sep 28 14:26:35 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memberInfo.password
     *
     * @mbg.generated Fri Sep 28 14:26:35 CST 2018
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberInfo.id
     *
     * @return the value of memberInfo.id
     *
     * @mbg.generated Fri Sep 28 14:26:35 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberInfo.id
     *
     * @param id the value for memberInfo.id
     *
     * @mbg.generated Fri Sep 28 14:26:35 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberInfo.username
     *
     * @return the value of memberInfo.username
     *
     * @mbg.generated Fri Sep 28 14:26:35 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberInfo.username
     *
     * @param username the value for memberInfo.username
     *
     * @mbg.generated Fri Sep 28 14:26:35 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column memberInfo.password
     *
     * @return the value of memberInfo.password
     *
     * @mbg.generated Fri Sep 28 14:26:35 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column memberInfo.password
     *
     * @param password the value for memberInfo.password
     *
     * @mbg.generated Fri Sep 28 14:26:35 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}