package com.example.demo.dao;

import com.example.demo.domain.Memberinfo;
import com.example.demo.domain.MemberinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface MemberinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberInfo
     *
     * @mbg.generated Fri Sep 28 14:26:35 CST 2018
     */
    long countByExample(MemberinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberInfo
     *
     * @mbg.generated Fri Sep 28 14:26:35 CST 2018
     */
    int deleteByExample(MemberinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberInfo
     *
     * @mbg.generated Fri Sep 28 14:26:35 CST 2018
     */
    @Delete({
        "delete from memberInfo",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberInfo
     *
     * @mbg.generated Fri Sep 28 14:26:35 CST 2018
     */
    @Insert({
        "insert into memberInfo (id, username, ",
        "password)",
        "values (#{id,jdbcType=INTEGER}, #{username,jdbcType=VARCHAR}, ",
        "#{password,jdbcType=VARCHAR})"
    })
    int insert(Memberinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberInfo
     *
     * @mbg.generated Fri Sep 28 14:26:35 CST 2018
     */
    int insertSelective(Memberinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberInfo
     *
     * @mbg.generated Fri Sep 28 14:26:35 CST 2018
     */
    List<Memberinfo> selectByExample(MemberinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberInfo
     *
     * @mbg.generated Fri Sep 28 14:26:35 CST 2018
     */
    @Select({
        "select",
        "id, username, password",
        "from memberInfo",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.example.demo.dao.MemberinfoMapper.BaseResultMap")
    Memberinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberInfo
     *
     * @mbg.generated Fri Sep 28 14:26:35 CST 2018
     */
    int updateByExampleSelective(@Param("record") Memberinfo record, @Param("example") MemberinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberInfo
     *
     * @mbg.generated Fri Sep 28 14:26:35 CST 2018
     */
    int updateByExample(@Param("record") Memberinfo record, @Param("example") MemberinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberInfo
     *
     * @mbg.generated Fri Sep 28 14:26:35 CST 2018
     */
    int updateByPrimaryKeySelective(Memberinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memberInfo
     *
     * @mbg.generated Fri Sep 28 14:26:35 CST 2018
     */
    @Update({
        "update memberInfo",
        "set username = #{username,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Memberinfo record);
}