package com.example.demo.dao;

import com.example.demo.domain.MiaoshaGoods;
import com.example.demo.domain.MiaoshaGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface MiaoshaGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_goods
     *
     * @mbg.generated Sun Sep 30 17:07:10 CST 2018
     */
    long countByExample(MiaoshaGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_goods
     *
     * @mbg.generated Sun Sep 30 17:07:10 CST 2018
     */
    int deleteByExample(MiaoshaGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_goods
     *
     * @mbg.generated Sun Sep 30 17:07:10 CST 2018
     */
    @Delete({
        "delete from miaosha_goods",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_goods
     *
     * @mbg.generated Sun Sep 30 17:07:10 CST 2018
     */
    @Insert({
        "insert into miaosha_goods (id, goods_id, ",
        "miaosha_price, stock_count, ",
        "start_date, end_date)",
        "values (#{id,jdbcType=INTEGER}, #{goodsId,jdbcType=INTEGER}, ",
        "#{miaoshaPrice,jdbcType=DECIMAL}, #{stockCount,jdbcType=INTEGER}, ",
        "#{startDate,jdbcType=TIMESTAMP}, #{endDate,jdbcType=TIMESTAMP})"
    })
    int insert(MiaoshaGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_goods
     *
     * @mbg.generated Sun Sep 30 17:07:10 CST 2018
     */
    int insertSelective(MiaoshaGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_goods
     *
     * @mbg.generated Sun Sep 30 17:07:10 CST 2018
     */
    List<MiaoshaGoods> selectByExample(MiaoshaGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_goods
     *
     * @mbg.generated Sun Sep 30 17:07:10 CST 2018
     */
    @Select({
        "select",
        "id, goods_id, miaosha_price, stock_count, start_date, end_date",
        "from miaosha_goods",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.example.demo.dao.MiaoshaGoodsMapper.BaseResultMap")
    MiaoshaGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_goods
     *
     * @mbg.generated Sun Sep 30 17:07:10 CST 2018
     */
    int updateByExampleSelective(@Param("record") MiaoshaGoods record, @Param("example") MiaoshaGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_goods
     *
     * @mbg.generated Sun Sep 30 17:07:10 CST 2018
     */
    int updateByExample(@Param("record") MiaoshaGoods record, @Param("example") MiaoshaGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_goods
     *
     * @mbg.generated Sun Sep 30 17:07:10 CST 2018
     */
    int updateByPrimaryKeySelective(MiaoshaGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_goods
     *
     * @mbg.generated Sun Sep 30 17:07:10 CST 2018
     */
    @Update({
        "update miaosha_goods",
        "set goods_id = #{goodsId,jdbcType=INTEGER},",
          "miaosha_price = #{miaoshaPrice,jdbcType=DECIMAL},",
          "stock_count = #{stockCount,jdbcType=INTEGER},",
          "start_date = #{startDate,jdbcType=TIMESTAMP},",
          "end_date = #{endDate,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(MiaoshaGoods record);
}